---
title: "Merge_VegBank_data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Impo

```{r}

library(readr)
library(readxl)
library(here)
library(tidyverse)
library(knitr)

# Paths to data
shared_data_dir <- "/home/shares/neon-inv"
data_raw <- file.path(shared_data_dir, "raw_VegBank_data")
data_output <- file.path(shared_data_dir, "output_files")

VegBank_AK_KPEACH_reduced  <- read_csv(file.path(data_output, "VegBank_AK_KPEACH_reduced.csv"))

VegBank_AL_KPEACH_reduced  <- read_csv(file.path(data_output, "VegBank_AL_KPEACH_reduced.csv"))

VegBank_FL_KPEACH_reduced  <- read_csv(file.path(data_output, "VegBank_FL_KPEACH_reduced.csv"))

VegBank_GA_KPEACH_reduced  <- read_csv(file.path(data_output, "VegBank_GA_KPEACH_reduced.csv"))

VegBank_MS_KPEACH_reduced  <- read_csv(file.path(data_output, "VegBank_MS_KPEACH_reduced.csv"))

VegBank_NC_coastal_KPEACH_reduced  <- read_csv(file.path(data_output, "VegBank_NC_coastal_KPEACH_reduced.csv"))

VegBank_NC_fringe_KPEACH_reduced  <- read_csv(file.path(data_output, "VegBank_NC_fringe_KPEACH_reduced.csv"))

VegBank_NCMts_KPEACH_reduced  <- read_csv(file.path(data_output, "VegBank_NCMts_KPEACH_reduced.csv"))

VegBank_NCPP_KPEACH_reduced  <- read_csv(file.path(data_output, "VegBank_NCPP_KPEACH_reduced.csv"))

VegBank_Proj129_KPEACH_reduced  <- read_csv(file.path(data_output, "VegBank_Proj129_KPEACH_reduced.csv"))

VegBank_SC_KPEACH_reduced  <- read_csv(file.path(data_output, "VegBank_SC_KPEACH_reduced.csv"))

VegBank_TN_KPEACH_reduced  <- read_csv(file.path(data_output, "VegBank_TN_KPEACH_reduced.csv"))

VegBank_TX_KPEACH_reduced  <- read_csv(file.path(data_output, "VegBank_TX_KPEACH_reduced.csv"))

VegBank_VA_KPEACH_reduced  <- read_csv(file.path(data_output, "VegBank_VA_KPEACH_reduced.csv"))

NCVS_WV_EB_reduced <- read_csv(file.path(data_output, "NCVS_WV_KPEACH_EB_reduced.csv"))


```


```{r}


df1 <-  merge(VegBank_AK_KPEACH_reduced, VegBank_AL_KPEACH_reduced, all = TRUE)

df2 <-  merge(df1, VegBank_FL_KPEACH_reduced, all = TRUE)

df3 <-  merge(df2, VegBank_GA_KPEACH_reduced, all = TRUE)

df4 <-  merge(df3, VegBank_MS_KPEACH_reduced, all = TRUE)

df5 <-  merge(df4, VegBank_NC_coastal_KPEACH_reduced, all = TRUE)

df6 <-  merge(df5, VegBank_NC_fringe_KPEACH_reduced, all = TRUE)

df7 <-  merge(df6, VegBank_NCMts_KPEACH_reduced, all = TRUE)

df8 <-  merge(df7, VegBank_NCPP_KPEACH_reduced, all = TRUE)

df9 <-  merge(df8, VegBank_Proj129_KPEACH_reduced, all = TRUE)

df10 <-  merge(df9, VegBank_SC_KPEACH_reduced, all = TRUE)

df11 <-  merge(df10, VegBank_TN_KPEACH_reduced, all = TRUE)

df12 <-  merge(df11, VegBank_TX_KPEACH_reduced, all = TRUE)

df13 <- merge(df12, VegBank_VA_KPEACH_reduced, all=TRUE)
glimpse(df13)
# clean up to match other datasets
df13 <- df13 %>% rename(ExoticStatus = NEW_ExoticStatus, GrowthForm = NEW_GrowthForm) %>%
  mutate(UniqueID = paste(Dataset, VegBankUniqueID, sep="_"))

All_VegBank_KPEACH_reduced <-  merge(df13, NCVS_WV_EB_reduced, all = TRUE)
glimpse(All_VegBank_KPEACH_reduced)


```

Quality Checks - fixing duplicate rows

```{r}

All_VegBank_KPEACH_reduced  <- unique(All_VegBank_KPEACH_reduced)

#unique(All_VegBank_KPEACH_031621$previousObsCode)
#No rows have a previous observation code so removing this column
All_VegBank_KPEACH_reduced <- All_VegBank_KPEACH_reduced %>% select(-'previousObsCode')

#Looking for duplicate rows. It looks like there are some semi-duplicate rows in the final merged data table (aka rows with the same SpCode and VegBankUniqueID but unique cover values). It looks like those came from 1 of 2 sources: 1. The data came with them. Someone accidentally input two rows for the same species with two different cover values. OR 2. When I renamed certain species it made two rows look like semi-duplicates. For example, a researcher may record a .5 cover value for  _Verbascum thapsus ssp. thapsus_ and a .3 cover value for  _Verbascum thapsus_ in the same plot and the same year. But _Verbascum thapsus_ does not have any subspecies according to USDA so I reduced _Verbascum thapsus ssp. thapsus_ to _Verbascum thapsus_ manually. Then those two rows would appear identical except for the cover value. 
duplicates <- All_VegBank_KPEACH_reduced %>% group_by(Dataset, UniqueID, SpCode) %>% summarise(n_obs = n()) %>% filter(n_obs > 1)
table(duplicates$Dataset) # not that many
# look at an example
All_VegBank_KPEACH_reduced %>% filter(Dataset=="NCVS_WV", SpCode=="ASTER", UniqueID=="SHMO.9") # family ID'd
All_VegBank_KPEACH_reduced %>% filter(UniqueID=="VEGBANK_NC_Coastal_057-09-0825", SpCode=="SCHIZ4") # probably multiple species of the same genus

# concerning if the pctcov measurements are the same, but if not I think we condense (ssp, genus, stuff like that)
duplicates = duplicates %>% mutate(check = paste(UniqueID, SpCode, sep=","))
check = All_VegBank_KPEACH_reduced %>% mutate(check = paste(UniqueID, SpCode, sep=",")) %>%
  filter(check %in% duplicates$check)

# looks like most are issues with varieties/subspecies reduced to same code, and missing info in woodiness column
# reduce to one measure of cover per species per plot
All_VegBank_KPEACH_reduced2 = All_VegBank_KPEACH_reduced %>% select(-Woodiness) %>% ungroup() %>% group_by(Dataset, Zone, Year, Lat, Long, `Taxon Observation Area`, bestname, SpCode, ExoticStatus, ExoticStatus_Origin, Duration, GrowthForm, UniqueID, VegBankUniqueID, `Public Latitude`, `Public Longitude`, `Sampling Level`) %>%
  summarise(PctCov = sum(PctCov)) # reduced about 200 rows

duplicates <- All_VegBank_KPEACH_reduced2 %>% ungroup() %>% group_by(Dataset, UniqueID, SpCode) %>% summarise(n_obs = n()) %>% filter(n_obs > 1)
table(duplicates$Dataset) # reduced most
duplicates = duplicates %>% mutate(check = paste(UniqueID, SpCode, sep=","))
check = All_VegBank_KPEACH_reduced2 %>% mutate(check = paste(UniqueID, SpCode, sep=",")) %>%
  filter(check %in% duplicates$check)

# remaining duplicates are issues with bestname including not all bestnames...'
# hard to tell if these are duplicates or distinct cover measurements
# checked for SC - they seem like distinct cover measurements... safe to condense
check_new = check %>% ungroup() %>% group_by(Dataset, Zone, Year, Lat, Long, `Taxon Observation Area`, SpCode, ExoticStatus, ExoticStatus_Origin, Duration, GrowthForm, UniqueID, VegBankUniqueID, `Public Latitude`, `Public Longitude`, `Sampling Level`) %>% summarise(PctCov = sum(PctCov))

# join actual bestname to code
codes <- read_csv("/home/shares/neon-inv/output_files/USDA_Plants_ScientificNames.csv")
codes = codes %>% select(Accepted.Symbol, Scientific.Name) %>% rename(SpCode=Accepted.Symbol, bestname=Scientific.Name) %>% distinct()
codes = codes[!duplicated(codes$SpCode),]
check_new = check_new %>% left_join(codes) %>% mutate(check = paste(UniqueID, SpCode, sep=","))

# drop old rows and add innew
All_VegBank_KPEACH_reduced3 = All_VegBank_KPEACH_reduced2 %>% mutate(check = paste(UniqueID,SpCode, sep=",")) %>%
  filter(!check %in% check_new$check)
All_VegBank_KPEACH_reduced3 = rbind(All_VegBank_KPEACH_reduced3, check_new)

```

Check other columns
```{r}

year_NAs <- All_VegBank_KPEACH_reduced3[is.na(All_VegBank_KPEACH_reduced3$Year),]

#looking for any unexpected values
unique(All_VegBank_KPEACH_reduced3$`Sampling Level`) # Only 4's and 5's which is what we wanted to see

unique(All_VegBank_KPEACH_reduced3$Year) #No NAs or weird dates

unique(All_VegBank_KPEACH_reduced3$`Taxon Observation Area`) # NAs and 0s...?

#No NA taxon observation area
taxon_obs_area_NAs <- All_VegBank_KPEACH_reduced3[is.na(All_VegBank_KPEACH_reduced3$`Taxon Observation Area`),] # bunch missing from EV
table(taxon_obs_area_NAs$Dataset)  # all WV
taxon_obs_area_0s <- All_VegBank_KPEACH_reduced3 %>% filter(`Taxon Observation Area`==0) # all WV also
# y dimension of plot is 0...wonder if those are transects

# not sure if missing vals were dropped from other datasets, but I'm okay with leaving them in for now

#Whew. 0 NA rows for bestname
bestname_NAs <- All_VegBank_KPEACH_reduced3[is.na(All_VegBank_KPEACH_reduced3$bestname),]

#0 rows with no cover data
pct_cov_NAs <- All_VegBank_KPEACH_reduced3[is.na(All_VegBank_KPEACH_reduced3$PctCov),]


```

Check to make sure codes are for accepted symbols using Ian's taxonomy
```{r}
tax <- read_csv(file.path(data_raw, "taxonomy_temp10_revised.csv"))
glimpse(tax)
All_VegBank_KPEACH_reduced3 %>% filter(SpCode %in% tax$Synonym.Symbol) # none! that's good
# drop check column
All_VegBank_KPEACH_reduced3 = All_VegBank_KPEACH_reduced3 %>% select(-check)

```

Check to see that each species has one assigned exotic status

```{r}
All_VegBank_KPEACH_reduced3 %>% filter(SpCode=="DESMO")

check_exo = All_VegBank_KPEACH_reduced3 %>% ungroup() %>% select(SpCode, ExoticStatus) %>% group_by(SpCode) %>%
  distinct() %>% summarise(n_exo = n()) %>% filter(n_exo > 1)
# 12 need to be fixed...
# exmaple to see if we need to condense cover...?
All_VegBank_KPEACH_reduced3 %>% filter(SpCode=="AMBRO") # exotic status missing from WV but we have it for others.. could be an error on my end
All_VegBank_KPEACH_reduced3 %>% filter(SpCode=="AMST80") # also best names are not always consistent...

check_name = All_VegBank_KPEACH_reduced3 %>% ungroup() %>% select(SpCode, bestname) %>% group_by(SpCode) %>%
  distinct() %>% summarise(n_exo = n()) %>% filter(n_exo > 1)

## EVE PICK UP HERE
  # 12 species codes that don't have consistent exotic status
  # There are a ton of species codes that do not have the right bestname

```


```{r}


  #As csv
write.csv(All_VegBank_KPEACH_reduced3,"/home/shares/neon-inv/output_files/All_VegBank_KPEACH_EB_reduced.csv", row.names = FALSE)

#write.csv(All_VegBank_KPEACH_reduced,"All_VegBank_KPEACH_reduced.csv", row.names = FALSE)


```

